permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: device-driver-pregen-check
jobs:
  device-driver-pregen-check:
    runs-on: ubuntu-latest
    name: device-driver-pregen-check
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install device-driver-cli from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: device-driver-cli
          version: 1.0.3
      - name: Generate files
        run: device-driver-cli --manifest device.yaml --device-name Registers -o ci_gen_registers.rs
      - name: Check that the files are the exact same
        uses: LouisBrunner/diff-action@v2.0.0
        with:
          old: ci_gen_registers.rs
          new: src/registers/generated.rs
          mode: strict
          tolerance: same